path_sound1 = {"startup":"audio/start_up.mp3",
                "lap":"audio/lap_san.mp3",
                "shiba":"audio/shiba_san.mp3",
                "bo":"audio/bo_san.mp3",
                "nam":"audio/nam_san.mp3",
                "hoan":"audio/hoan_san.mp3",
                "cuong":"audio/cuong_san.mp3",
                "chung":"audio/chung_san.mp3",
                "thao":"audio/thao_san.mp3",
                "nha":"audio/nha_san.mp3",
                "son":"audio/son_san.mp3",
                "long":"audio/long_san.mp3",
                "phuong":"audio/phuong_san.mp3",
                "thuc":"audio/thuc_san.mp3",
                "ha":"audio/ha_san.mp3"}
path_sound2 = {"startup":"audio/start_up.mp3",
                "lap":"audio/tam_biet_lap.mp3",
                "shiba":"audio/tam_biet_shiba.mp3",
                "bo":"audio/tam_biet_bo.mp3",
                "nam":"audio/tam_biet_nam.mp3",
                "hoan":"audio/tam_biet_hoan.mp3",
                "cuong":"audio/tam_biet_cuong.mp3",
                "chung":"audio/tam_biet_chung.mp3",
                "thao":"audio/tam_biet_thao.mp3",
                "nha":"audio/tam_biet_nha.mp3",
                "son":"audio/tam_biet_son.mp3",
                "long":"audio/tam_biet_long.mp3",
                "phuong":"audio/tam_biet_phuong.mp3",
                "thuc":"audio/tam_biet_thuc.mp3",
                "ha":"audio/tam_biet_ha.mp3"}
id_name={"lap":"e6184",
         "shiba":"e1111",
         "bo":"0001",
         "nam":"0002",
         "hoan":"0003",
         "cuong":"0004",
         "chung":"0005",
         "thao":"0006",
         "nha":"0007",
         "son":"0010",
         "long":"0011",
         "phuong":"0012",
         "thuc":"0013",
         "ha":"0014"}
local = {"host":"localhost",
         "user":"leevawns",
         "password":"123",
         "database":"face_detect"}
server = {"host":"192.168.0.124",
          "user":"lap",
          "password":"25021993",
          "database":""}
config_default = {"local":local,"server":server}